version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - PORT=4000
      - BACKEND_DB_PATH=/data/dev.sqlite
      - FRONTEND_ORIGIN=http://localhost:5173
    volumes:
      - ./backend/data:/data
    ports:
      - "4000:4000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - VITE_API_URL=http://localhost:4000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend

# Placeholder
